dist: xenial   # required for Python >= 3.7
language: python
addons:
  artifacts: true

python:
  - "3.7"

# command to install dependencies
install: &requirements
  - pip install -r requirements-no-gpu.txt
  - pip install -e .

jobs:
    include:
      - stage: Tests
        install: *requirements
        script:
          - pip install codecov
          - bash -c "pip --no-cache-dir install --upgrade git+https://github.com/thisch/pytest-sphinx.git pytest"
          # install pytest coverage extension
          - pip --no-cache-dir install pytest-cov
          - module=""
          - for d in $(ls -d */); do if [ -f "$d"__init__.py ]; then module=${d::-1}; fi done
          - pytest -x -s -vvv --doctest-modules $module --cov=$module
        # Push the results back to codecov
        after_success:
          - codecov
      - stage: Black
        install: *requirements
        script:
          # printing modules to exclude
          - echo excluding $(git config --file .gitmodules --get-regexp path | awk '{ print $2 }')
          # exclude submodules from black
          - black --exclude $(git config --file .gitmodules --get-regexp path | awk '{ print $2 }') --check .
      - stage: Pylint
        install: *requirements
        script:
          - pip --no-cache-dir install pylint-runner
          - bash -c "pylint_runner --rcfile=.pylintrc --output-format=text . | tee pylint.txt"
          - score=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint.txt)
