dist: xenial   # required for Python >= 3.7
language: python

python:
  - "3.7"

# command to install dependencies
install: &requirements
  - pip install -r requirements-no-gpu.txt
  - pip install -e .

jobs:
    include:
      - stage: Tests
        install: *requirements
        script:
          - bash -c "pip --no-cache-dir install --upgrade git+https://github.com/thisch/pytest-sphinx.git pytest"
          # install pytest coverage extension
          - pip --no-cache-dir install pytest-cov
          - module=""
          - for d in $(ls -d */); do if [ -f "$d"__init__.py ]; then module=${d::-1}; fi done
          - pytest -x -s -vvv --doctest-modules $module --cov=$module
